language: python
python:
  - 3.5
  - 3.6
cache: pip
install: "pip install -r requirements.txt && python setup.py develop && pip install coverage"
script: coverage run setup.py test
after_success:
  - coveralls
