language: python
python:
  - 3.5
  - 3.6
cache: pip
install:
  - pip install -r requirements.txt
  - pip install coverage python-coveralls
  - python setup.py install
script: coverage run setup.py test
after_success:
  - coveralls
